dataset_config:
  name: count-neighbours-type
  params:
    num_nodes: 1600
    avg_degree: 10
    num_classes: 4
    label_type: 'least-common'
training_config:
  n_epochs: 1000
  patience: 100
model_config:
  class: baseline_models.GraphSAGE
  params:
    n_layers: [2, 3, 4, 5]
    num_hidden_channels: [2, 5, 10, 20] #, 50]
    augmented: [False, True]
    aggr: ['mean', 'max']
    concat_ego_neigh_embs: False #[False, True]
    p_dropout: 0 #[0, 0.2, 0.5]
    skip_connections: [False, True]
    p_input_dropout: 0 #[0, 0.2, 0.4, 0.6, 0.8]
optimiser_config:
  class: torch.optim.Adam
  params:
    lr: 0.01
    weight_decay: 0 #0.0001 #[0.001, 0.0001]